#!/usr/bin/env python3
"""Generate one `.dax` test file per measure from `Status=Approved` registry rows.

Usage:
    uv run generate_measure_tests.py <registry.csv> --output-dir <DAXQueries dir> \
        [--dax-queries-json <path to daxQueries.json>] [--json]

Behavior (see ../references/certification-registry-schema.md and the
`powerbi/dax-unit-testing` capability's Deterministic Test Generation requirement):

- Only `Status=Approved` rows are generated. `Pending` rows are skipped and reported as
  `CERTIFICATION_PENDING`. `Retired` rows are skipped silently (expected, not a failure).
- Generation is idempotent: identical registry input produces byte-identical `.dax` output.
- Each generated file carries a `DO NOT EDIT BY HAND` header and a content-hash marker. If a
  previously generated file's body no longer matches its stored hash (i.e. it was hand-edited),
  generation refuses to overwrite it and reports `GENERATED_FILE_MODIFIED` instead.
- Every generated file is registered in `daxQueries.json` exactly once; pre-existing entries are
  preserved untouched, and a second identical run leaves `daxQueries.json` byte-identical.
"""
from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import re
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _registry_common import (  # noqa: E402
    Finding,
    RegistryError,
    read_registry_rows,
    sanitize_filename_component,
)

HEADER_LINE_1 = "// DO NOT EDIT BY HAND — generated by dax-unit-testing/assets/scripts/generate_measure_tests.py"
HEADER_LINE_2 = "// Source registry: Certification/MeasureCertification.csv"
_HASH_LINE_RE = re.compile(r"^// content-hash: ([0-9a-f]{16})$")

# Fixed namespace so generated daxQueries.json `queryId` values are deterministic across runs.
_QUERY_ID_NAMESPACE = uuid.UUID("6f7c7b1e-6f3b-4c1a-9e3a-2a2f6b1d1234")


def _format_number(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return text if text else "0"


def build_assertion_call(measure_name: str, row: dict) -> str:
    test_name = row["TestName"].replace('"', '""')
    filter_expr = (row.get("FilterExpression") or "").strip()
    expr = f"[{measure_name}]" if not filter_expr else f"CALCULATE([{measure_name}], {filter_expr})"

    if row["TestCategory"] == "Structural":
        return f'PQL.Assert.ShouldNotBeNullOrBlank("{test_name}", {expr})'

    expected = (row.get("ExpectedValue") or "").strip()
    if expected == "NOT_BLANK":
        return f'PQL.Assert.ShouldNotBeNullOrBlank("{test_name}", {expr})'
    if expected == ">=0":
        return f'PQL.Assert.ShouldBeGreaterOrEqual("{test_name}", 0, {expr})'
    if expected == ">0":
        return f'PQL.Assert.ShouldBeGreaterThan("{test_name}", 0, {expr})'

    try:
        tolerance = float(row.get("Tolerance") or "0")
    except ValueError:
        tolerance = 0.0
    if tolerance > 0:
        try:
            value = float(expected)
        except ValueError:
            value = 0.0
        lower, upper = _format_number(value - tolerance), _format_number(value + tolerance)
        return f'PQL.Assert.ShouldBeBetween("{test_name}", {lower}, {upper}, {expr})'
    return f'PQL.Assert.ShouldEqual("{test_name}", {expected}, {expr})'


def build_dax_body(measure_name: str, rows: list[dict]) -> str:
    calls = [build_assertion_call(measure_name, row) for row in sorted(rows, key=lambda r: r["TestName"])]
    joined = ",\n    ".join(calls)
    return f"EVALUATE\nUNION(\n    {joined}\n)\n"


def build_file_content(measure_name: str, rows: list[dict]) -> str:
    body = build_dax_body(measure_name, rows)
    content_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()[:16]
    header = f"{HEADER_LINE_1}\n{HEADER_LINE_2}\n// content-hash: {content_hash}\n"
    return header + body


def split_generated_file(text: str) -> tuple[str | None, str]:
    """Return (stored_hash, body) if `text` matches the generator's own header shape."""
    lines = text.splitlines(keepends=True)
    if len(lines) < 3:
        return None, text
    if lines[0].rstrip("\n") != HEADER_LINE_1 or lines[1].rstrip("\n") != HEADER_LINE_2:
        return None, text
    m = _HASH_LINE_RE.match(lines[2].rstrip("\n"))
    if not m:
        return None, text
    return m.group(1), "".join(lines[3:])


def generate(registry_path: Path, output_dir: Path) -> tuple[list[str], list[Finding]]:
    _, rows = read_registry_rows(registry_path)

    by_measure: dict[str, list[dict]] = {}
    findings: list[Finding] = []
    for row in rows:
        status = row.get("Status", "")
        if status == "Pending":
            findings.append(Finding(
                error_type="CERTIFICATION_PENDING",
                message="Row is Status=Pending; skipped by generation.",
                measure_name=row.get("MeasureName", ""), test_name=row.get("TestName", ""),
            ))
            continue
        if status == "Retired":
            continue  # expected exclusion, not a failure
        if status != "Approved":
            continue
        by_measure.setdefault(row["MeasureName"], []).append(row)

    output_dir.mkdir(parents=True, exist_ok=True)
    written_files: list[str] = []
    for measure_name in sorted(by_measure):
        measure_rows = by_measure[measure_name]
        filename = f"{sanitize_filename_component(measure_name)}.ANY.Tests.dax"
        path = output_dir / filename
        content = build_file_content(measure_name, measure_rows)

        if path.exists():
            existing_text = path.read_text(encoding="utf-8")
            stored_hash, existing_body = split_generated_file(existing_text)
            if stored_hash is None:
                findings.append(Finding(
                    error_type="GENERATED_FILE_MODIFIED",
                    message=f"{filename} already exists and was not created by this generator; refusing to overwrite.",
                    measure_name=measure_name,
                ))
                continue
            actual_hash = hashlib.sha256(existing_body.encode("utf-8")).hexdigest()[:16]
            if actual_hash != stored_hash:
                findings.append(Finding(
                    error_type="GENERATED_FILE_MODIFIED",
                    message=f"{filename} was hand-edited since the last generation; refusing to overwrite.",
                    measure_name=measure_name,
                ))
                continue

        with path.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        written_files.append(filename)

    return written_files, findings


def update_dax_queries_json(json_path: Path, generated_filenames: list[str]) -> None:
    if json_path.exists():
        data = json.loads(json_path.read_text(encoding="utf-8"))
    else:
        data = {"version": "1.0", "queries": []}
    if not isinstance(data.get("queries"), list):
        data["queries"] = []

    existing_files = {q.get("queryFile") for q in data["queries"] if isinstance(q, dict)}
    for filename in sorted(generated_filenames):
        if filename in existing_files:
            continue
        query_id = str(uuid.uuid5(_QUERY_ID_NAMESPACE, filename))
        data["queries"].append({"queryFile": filename, "queryId": query_id})

    json_path.parent.mkdir(parents=True, exist_ok=True)
    with json_path.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(json.dumps(data, indent=2))
        fh.write("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("registry", type=Path)
    parser.add_argument("--output-dir", type=Path, required=True, help="Target DAXQueries/ folder")
    parser.add_argument("--dax-queries-json", type=Path, default=None, help="Path to daxQueries.json (defaults to <output-dir>/daxQueries.json)")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    if not args.registry.exists():
        print(f"error: registry file not found: {args.registry}", file=sys.stderr)
        return 2

    dax_queries_json = args.dax_queries_json or (args.output_dir / "daxQueries.json")

    try:
        written_files, findings = generate(args.registry, args.output_dir)
    except RegistryError as exc:
        findings = [exc.finding]
        written_files = []

    if written_files:
        update_dax_queries_json(dax_queries_json, written_files)

    hard_failures = [f for f in findings if f.error_type == "GENERATED_FILE_MODIFIED"]

    result = {
        "registry": str(args.registry),
        "outputDir": str(args.output_dir),
        "generatedFiles": written_files,
        "findings": [dataclasses.asdict(f) for f in findings],
    }
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"Generated {len(written_files)} file(s) in {args.output_dir}: {written_files}")
        for f in findings:
            print(f"  {f}")

    return 1 if hard_failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
