"""Post or update a sticky Azure DevOps PR comment thread.

Azure DevOps has no `gh pr comment` equivalent, so this mirrors the GitHub
Actions workflow's "find comment by marker, PATCH it, else create it" logic
against the Azure DevOps Git Pull Request Threads REST API. Stdlib-only
(urllib) so no extra pip install is needed in the pipeline.

API docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-threads
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional

API_VERSION = "7.1"


def _request(url: str, token: str, method: str = "GET", body: Optional[dict] = None):
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    req.add_header("Accept", "application/json")
    try:
        with urllib.request.urlopen(req) as resp:
            raw = resp.read()
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        print(f"error: {method} {url} -> {exc.code}\n{detail}", file=sys.stderr)
        raise


def find_marked_thread(threads: list, marker: str) -> Optional[dict]:
    for thread in threads:
        comments = thread.get("comments") or []
        if comments and str(comments[0].get("content", "")).startswith(marker):
            return thread
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Post/update a sticky Azure DevOps PR comment.")
    parser.add_argument("--org-uri", required=True, help="e.g. https://dev.azure.com/myorg/")
    parser.add_argument("--project", required=True)
    parser.add_argument("--repo-id", required=True, help="Repository ID or name.")
    parser.add_argument("--pr-id", required=True)
    parser.add_argument("--summary-file", required=True, type=Path)
    parser.add_argument("--marker", default="<!-- pbip-change-summary-marker -->")
    parser.add_argument("--token", default="", help="Falls back to $SYSTEM_ACCESSTOKEN env var.")

    args = parser.parse_args()

    token = args.token or os.environ.get("SYSTEM_ACCESSTOKEN", "")
    if not token:
        print("error: no token provided (--token or $SYSTEM_ACCESSTOKEN)", file=sys.stderr)
        return 2

    summary_text = args.summary_file.read_text(encoding="utf-8")
    body_lines = [line for line in summary_text.splitlines() if line.strip()]
    if len(body_lines) <= 1:
        print("Nothing of substance changed; skipping comment.")
        return 0

    content = (
        f"{args.marker}\n\n{summary_text}\n\n"
        "_Auto-generated by the PBIP change-summary pipeline. "
        "Pushes to this PR refresh this comment._"
    )

    org_uri = args.org_uri.rstrip("/")
    base = f"{org_uri}/{args.project}/_apis/git/repositories/{args.repo_id}/pullRequests/{args.pr_id}/threads"

    threads_resp = _request(f"{base}?api-version={API_VERSION}", token)
    existing = find_marked_thread(threads_resp.get("value", []), args.marker)

    if existing:
        thread_id = existing["id"]
        comment_id = existing["comments"][0]["id"]
        url = f"{base}/{thread_id}/comments/{comment_id}?api-version={API_VERSION}"
        _request(url, token, method="PATCH", body={"content": content})
        print(f"Updated sticky comment thread {thread_id}")
        return 0

    body = {
        "comments": [{"parentCommentId": 0, "content": content, "commentType": 1}],
        "status": 1,  # active
    }
    created = _request(f"{base}?api-version={API_VERSION}", token, method="POST", body=body)
    print(f"Created sticky comment thread {created.get('id')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
